### ISSUE TITLE
Converter does not support Postman Folders

### ISSUE THREAD

**Issue by iwcorplab** [sercheo87/convert-postman-jmeter#12]
Hi there! Thanks for this very useful tool, I don't know if this a bug or a Feature Request, but here it goes:

It is not possible to convert a Postman Collection to JMX if the requests inside the Collection are organized in folders.

**To Reproduce**
1. Create a Postman Collection containg at least one folder with requests
2.  From Postman export the Collection to .json file
3.- Use converter to convert the .json to a Jmeter project (example command: "convert-postman-jmeter -p postmanCollectionWithFolders.json"

**Expected behavior**
Collection is exported as JMX files, regarding if the project contains folders. 

**Additional context**
This is the result:

Starting convert...
Read file: C:\Users\*********\Desktop\KCenter\APITests\*******.postman_collection.json
C:\Users\******\AppData\Roaming\npm\node_modules\convert-postman-jmeter\lib\convert-postman-jmeter.js:56
          const urlItem = item.request.url;
                                       ^

**TypeError: Cannot read property 'url' of undefined**
    at C:\Users\********\AppData\Roaming\npm\node_modules\convert-postman-jmeter\lib\convert-postman-jmeter.js:56:40
    at Array.forEach (<anonymous>)
    at Object.convertProject [as convert] (C:\Users\******\AppData\Roaming\npm\node_modules\convert-postman-jmeter\lib\convert-postman-jmeter.js:55:26)
    at Object.<anonymous> (C:\Users\*******\AppData\Roaming\npm\node_modules\convert-postman-jmeter\bin\convert-postman-jmeter:26:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by chara-art** [comment]
Hello, same issue 
TypeError: Cannot read property 'url' of undefined
    at C:\Users\******\AppData\Roaming\npm\node_modules\convert-postman-jmeter\lib\convert-postman-jmeter.js:56:40
    at Array.forEach (<anonymous>)
    at Object.convertProject [as convert] (C:\Users\c.***8\AppData\Roaming\npm\node_modules\convert-postman-jmeter\lib\convert-postman-jmeter.js:55:26)
    at Object.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\convert-postman-jmeter\bin\convert-postman-jmeter:26:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
