### ISSUE TITLE
Unable to see the collection imported in jmeter along with the Body data (I have used multi form in postman)

### ISSUE THREAD

**Issue by muralinambi** [sercheo87/convert-postman-jmeter#141]
**Describe the bug**
 Header and body content form data is not seen in Jmeter once i used this command to export postman to jmeter .I have used this script `convert-postman-jmeter -p ./postman_collection.json -j ./jmeter_test_plan.jmx -e ./postman_environment.json`
 

**To Reproduce**
1. I have the postman collection
2. Successfuly imported to Jmeter
3. I also see the test plan in jmeter 
4. Error loading environment file Error: ENOENT: no such file or directory, open './postman_environment.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at loadFileEnvironmentProject (/usr/local/lib/node_modules/convert-postman-jmeter/lib/convert-postman-jmeter.js:68:31)
    at loadEnvironmentFile (/usr/local/lib/node_modules/convert-postman-jmeter/lib/convert-postman-jmeter.js:95:35)
    at exportByProject (/usr/local/lib/node_modules/convert-postman-jmeter/lib/convert-postman-jmeter.js:198:26)
    at Object.convertProject [as convert] (/usr/local/lib/node_modules/convert-postman-jmeter/lib/convert-postman-jmeter.js:267:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/convert-postman-jmeter/bin/convert-postman-jmeter:40:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './postman_environment.json'

**Expected behavior**
Why the body content form data is not auto generated in Jmeter . 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AntonioSun** [comment]
What would it happen if you remove the `-e ./postman_environment.json` from your command line?

as it is not Required.

**Comment by sercheo87** [comment]
HI, the command option `-e` use it only you have a project postman with variables inside, if it is not your case, this is not required.

The problem see is the file `postman_environment.json` not exist.

Try to execute with this command line in your

```bash
convert-postman-jmeter -p ./postman_collection.json -j ./jmeter_test_plan.jmx
```

**Comment by sercheo87** [comment]
it's closed this issue by inactivity
